accelerator: null
accumulate_grad_batches: 1
adafactor: false
adam_epsilon: 1.0e-08
amp_backend: native
amp_level: O2
attention_dropout: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
automatic_optimization: true
benchmark: false
cache_dir: ''
check_val_every_n_epoch: 1
checkpoint_callback: true
config_name: ''
data_dir: /content/drive/My Drive/CS196Project/Group6/finetuning/example_data
decoder_layerdrop: null
default_root_dir: null
deterministic: false
distributed_backend: null
do_predict: false
do_train: true
dropout: null
early_stopping_patience: -1
encoder_layerdrop: null
eval_batch_size: 32
eval_beams: null
eval_max_gen_length: null
fast_dev_run: false
flush_logs_every_n_steps: 100
fp16: true
fp16_opt_level: O2
freeze_embeds: true
freeze_encoder: true
gpus: 1
gradient_clip_val: 0
label_smoothing: 0.0
learning_rate: 3.0e-05
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
logger_name: default
lr_scheduler: linear
max_epochs: 6
max_source_length: 1024
max_steps: null
max_target_length: 20
max_tokens_per_batch: null
min_epochs: 1
min_steps: null
model_name_or_path: facebook/bart-large
n_test: -1
n_train: -1
n_val: 100
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_workers: 4
output_dir: example_output
overfit_batches: 0.0
overwrite_output_dir: false
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
save_top_k: 1
seed: 42
sortish_sampler: false
src_lang: ''
sync_batchnorm: false
task: summarization
terminate_on_nan: false
test_max_target_length: 20
tgt_lang: ''
tokenizer_name: null
tpu_cores: !!python/name:pytorch_lightning.utilities.argparse_utils._gpus_arg_default ''
track_grad_norm: -1
train_batch_size: 1
truncated_bptt_steps: null
val_check_interval: 0.1
val_max_target_length: 60
val_metric: null
warmup_steps: 0
weight_decay: 0.0
weights_save_path: null
weights_summary: top
